New version
asseco-voice/laravel-content-driver pull request #4
Opened 2021-07-19 13:09 UTC by assefvisic

2021-07-20 13:15 UTC, Norgul requested changes

2021-07-20 13:15 UTC, Norgul commented on phpunit.xml
> +        <server name="FILESYSTEM_BASE_URL" value="http://live-content:8080/v1/content/"/>
Ako nema podignutog servisa ovo neće proći, možemo li to nekako drugačije?

2021-07-20 13:15 UTC, Norgul commented on src/ContentAdapter.php
> +    public function read($path)
Zašto nemamo više return type?

Iako nije u ovom PRu, `write()` metoda ne valja, `delete() rename() copy()`...i ostali...imaju krivi return type i dalje

2021-07-20 13:15 UTC, Norgul commented on tests/TestCase.php
> +        return Iam::getServiceToken();
Iam je klasa iz šasije, to ne smije biti tu.

2021-07-20 13:15 UTC, Norgul commented on tests/Unit/ClientTest.php
> +//    /**
Zašto su svi testovi zakomentirani?

2021-07-20 13:19 UTC, Norgul commented
`ContentClient` konstruktor ne valja zadnji parametar.
Postoje metode `uploadFile` i `uploadFFile`...to pretpostavljam ne valja?
`upload()` metoda ne valja

2021-07-22 12:15 UTC, assefvisic commented on phpunit.xml
> +        <server name="FILESYSTEM_BASE_URL" value="http://live-content:8080/v1/content/"/>
imaš neki prijedlog? 
da sve za test prebacim u šasiju?

2021-07-22 12:15 UTC, assefvisic commented on tests/TestCase.php
> +        return Iam::getServiceToken();
gdje trebam staviti IAM? 
negdje kod incializije moram ga poslati, inace ga ne mogu koristiti
možda ovo sve treba biti u šasiji da nije paket?

2021-07-22 13:01 UTC, closed without merging